In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from IPython.core.display import display
import matplotlib.pyplot as plt
import os
print(os.listdir("../input"))

['bureau_balance.csv', 'application_test.csv', 'installments_payments.csv', 'application_train.csv', 'POS_CASH_balance.csv', 'sample_submission.csv', 'bureau.csv', 'credit_card_balance.csv', 'previous_application.csv']

In [2]:
train = pd.read_csv('../input/application_train.csv')
bb = pd.read_csv('../input/bureau_balance.csv')
b = pd.read_csv('../input/bureau.csv')
ccb = pd.read_csv('../input/credit_card_balance.csv')
ip = pd.read_csv('../input/installments_payments.csv')
pa = pd.read_csv('../input/previous_application.csv')
pcb = pd.read_csv('../input/POS_CASH_balance.csv')

In [3]:
train.head()

   SK_ID_CURR             ...              AMT_REQ_CREDIT_BUREAU_YEAR
0      100002             ...                                     1.0
1      100003             ...                                     0.0
2      100004             ...                                     0.0
3      100006             ...                                     NaN
4      100007             ...                                     0.0

[5 rows x 122 columns]

In [4]:
display(bb.head(), len(bb))

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

27299925

In [5]:
display(b.head(), len(b))

   SK_ID_CURR  SK_ID_BUREAU     ...     DAYS_CREDIT_UPDATE AMT_ANNUITY
0      215354       5714462     ...                   -131         NaN
1      215354       5714463     ...                    -20         NaN
2      215354       5714464     ...                    -16         NaN
3      215354       5714465     ...                    -16         NaN
4      215354       5714466     ...                    -21         NaN

[5 rows x 17 columns]

1716428

In [6]:
display(ccb.head(), len(ccb))

   SK_ID_PREV  SK_ID_CURR     ...      SK_DPD  SK_DPD_DEF
0     2562384      378907     ...           0           0
1     2582071      363914     ...           0           0
2     1740877      371185     ...           0           0
3     1389973      337855     ...           0           0
4     1891521      126868     ...           0           0

[5 rows x 23 columns]

3840312

In [7]:
display(ip.head(), len(ip))

   SK_ID_PREV  SK_ID_CURR     ...       AMT_INSTALMENT  AMT_PAYMENT
0     1054186      161674     ...             6948.360     6948.360
1     1330831      151639     ...             1716.525     1716.525
2     2085231      193053     ...            25425.000    25425.000
3     2452527      199697     ...            24350.130    24350.130
4     2714724      167756     ...             2165.040     2160.585

[5 rows x 8 columns]

13605401

In [8]:
display(pa.head(), len(pa))

   SK_ID_PREV            ...              NFLAG_INSURED_ON_APPROVAL
0     2030495            ...                                    0.0
1     2802425            ...                                    1.0
2     2523466            ...                                    1.0
3     2819243            ...                                    1.0
4     1784265            ...                                    NaN

[5 rows x 37 columns]

1670214

In [9]:
display(pcb.head(), len(pcb))

   SK_ID_PREV  SK_ID_CURR     ...      SK_DPD  SK_DPD_DEF
0     1803195      182943     ...           0           0
1     1715348      367990     ...           0           0
2     1784872      397406     ...           0           0
3     1903291      269225     ...           0           0
4     2341044      334279     ...           0           0

[5 rows x 8 columns]

10001358

In [10]:
pa_pcb = pd.merge(pa, pcb, on='SK_ID_PREV')

In [11]:
display(pa_pcb.head(100), len(pa_pcb))

    SK_ID_PREV  SK_ID_CURR_x     ...     SK_DPD  SK_DPD_DEF
0      2030495        271877     ...          0           0
1      2030495        271877     ...          0           0
2      2802425        108129     ...          0           0
3      2802425        108129     ...          0           0
4      2802425        108129     ...          0           0
5      2802425        108129     ...          0           0
6      2802425        108129     ...          0           0
7      2523466        122040     ...          0           0
8      2523466        122040     ...          0           0
9      2523466        122040     ...          0           0
10     2523466        122040     ...          0           0
11     2523466        122040     ...          0           0
12     2523466        122040     ...          0           0
13     2523466        122040     ...          0           0
14     2523466        122040     ...          0           0
15     2523466        122040     ...          0           0
16     2523466        122040     ...          0           0
17     2819243        176158     ...          0           0
18     2819243        176158     ...          0           0
19     2819243        176158     ...          0           0
20     2819243        176158     ...          0           0
21     2819243        176158     ...          0           0
22     2819243        176158     ...          0           0
23     2819243        176158     ...          0           0
24     2819243        176158     ...          0           0
25     2819243        176158     ...          0           0
26     2819243        176158     ...          0           0
27     2819243        176158     ...          0           0
28     2819243        176158     ...          0           0
29     1383531        199383     ...          0           0
..         ...           ...     ...        ...         ...
70     2330894        258628     ...          0           0
71     2330894        258628     ...          0           0
72     2330894        258628     ...          0           0
73     2330894        258628     ...          0           0
74     2330894        258628     ...          0           0
75     2330894        258628     ...          0           0
76     2330894        258628     ...          0           0
77     2330894        258628     ...          0           0
78     2330894        258628     ...          0           0
79     2330894        258628     ...          0           0
80     2330894        258628     ...          0           0
81     2330894        258628     ...          0           0
82     2330894        258628     ...          0           0
83     2330894        258628     ...          0           0
84     2330894        258628     ...          0           0
85     2330894        258628     ...          0           0
86     2330894        258628     ...          0           0
87     2330894        258628     ...          0           0
88     2330894        258628     ...          0           0
89     1397919        321676     ...          0           0
90     1397919        321676     ...          0           0
91     1397919        321676     ...          0           0
92     1397919        321676     ...          0           0
93     1397919        321676     ...          0           0
94     1397919        321676     ...          0           0
95     1397919        321676     ...          0           0
96     1397919        321676     ...          0           0
97     1397919        321676     ...          0           0
98     2273188        270658     ...          0           0
99     2273188        270658     ...          0           0

[100 rows x 44 columns]

9660797

In [12]:
pa_pcb['NAME_CONTRACT_TYPE'].value_counts()

Consumer loans    5997319
Cash loans        3663478
Name: NAME_CONTRACT_TYPE, dtype: int64

In [13]:
print(f"欠損値割合:{pa_pcb['NAME_CONTRACT_TYPE'].isnull().count() / len(pa_pcb['NAME_CONTRACT_TYPE']) *100 - 100}%")

欠損値割合:0.0%

ToDo  
NAME_CONTRACT_TYPEを0,1で書き換えていく