In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 100)

In [2]:
ip = pd.read_csv('data/installments_payments.csv', error_bad_lines=False)
ccb = pd.read_csv('data/credit_card_balance.csv', error_bad_lines=False)

pcb = pd.read_csv('data/POS_CASH_balance.csv', error_bad_lines=False)

pa = pd.read_csv('data/previous_application.csv', error_bad_lines=False)

p = pd.read_csv('data/bureau.csv', error_bad_lines=False)
bb = pd.read_csv('data/bureau_balance.csv', error_bad_lines=False)

test = pd.read_csv('data/application_test.csv', error_bad_lines=False)
train = pd.read_csv('data/application_train.csv', error_bad_lines=False)

b'Skipping line 39462: expected 8 fields, saw 10\n'
b'Skipping line 118361: expected 8 fields, saw 13\n'
b'Skipping line 295936: expected 8 fields, saw 9\n'
/root/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [30]:
ccb_ip = pd.merge(ccb, ip, on=['SK_ID_PREV', 'SK_ID_CURR'])
ccb_ip_pcb = pd.merge(ccb_ip, pcb, on=['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 
                                       'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF'])
ccb_ip_pcb_pa = pd.merge(ccb_ip_pcb, pa, on='SK_ID_PREV')

p_bb = pd.merge(p, bb, on='SK_ID_BUREAU')

In [18]:
ccb_ip.head()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1891521,126868,-1.0,453919.455,450000.0,0.0,11547.0,0.0,11547.0,22924.89,27000.0,27000.0,443044.395,453919.455,453919.455,0.0,1.0,0.0,1.0,101.0,Active,0.0,0.0,0,137.0,-996,-996.0,7549.56,7549.56
1,1891521,126868,-1.0,453919.455,450000.0,0.0,11547.0,0.0,11547.0,22924.89,27000.0,27000.0,443044.395,453919.455,453919.455,0.0,1.0,0.0,1.0,101.0,Active,0.0,0.0,0,176.0,-378,-391.0,22570.74,22570.74
2,1891521,126868,-1.0,453919.455,450000.0,0.0,11547.0,0.0,11547.0,22924.89,27000.0,27000.0,443044.395,453919.455,453919.455,0.0,1.0,0.0,1.0,101.0,Active,0.0,0.0,0,90.0,-1689,-1689.0,4500.00,4500.00
3,1891521,126868,-1.0,453919.455,450000.0,0.0,11547.0,0.0,11547.0,22924.89,27000.0,27000.0,443044.395,453919.455,453919.455,0.0,1.0,0.0,1.0,101.0,Active,0.0,0.0,0,57.0,-2163,-2182.0,9000.00,9000.00
4,1891521,126868,-1.0,453919.455,450000.0,0.0,11547.0,0.0,11547.0,22924.89,27000.0,27000.0,443044.395,453919.455,453919.455,0.0,1.0,0.0,1.0,101.0,Active,0.0,0.0,0,57.0,-2163,-2182.0,9000.00,9000.00

In [33]:
ccb_ip_pcb.head()

Empty DataFrame
Columns: [SK_ID_PREV, SK_ID_CURR, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECIVABLE, AMT_TOTAL_RECEIVABLE, CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT, AMT_INSTALMENT, AMT_PAYMENT, CNT_INSTALMENT, CNT_INSTALMENT_FUTURE]
Index: []

Empty DataFrame
Columns: [SK_ID_PREV, SK_ID_CURR_x, MONTHS_BALANCE_x, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT, AMT_INST_MIN_REGULARITY, AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECIVABLE, AMT_TOTAL_RECEIVABLE, CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT, CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS_x, SK_DPD_x, SK_DPD_DEF_x, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT, AMT_INSTALMENT, AMT_PAYMENT, SK_ID_CURR_y, MONTHS_BALANCE_y, CNT_INSTALMENT, CNT_INSTALMENT_FUTURE, NAME_CONTRACT_STATUS_y, SK_DPD_y, SK_DPD_DEF_y]
Index: []

In [8]:
just_before = pd.merge(ccb_ip_pcb_pa, p_bb, on='SK_ID_PREV')

KeyError: 'SK_ID_PREV'